"""add fields to plugin

Revision ID: 16cdfe17a8f1
Revises: 0836f3ddacaf
Create Date: 2024-06-24 12:04:15.090792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import AutoString

# revision identifiers, used by Alembic.
revision: str = '16cdfe17a8f1'
down_revision: Union[str, None] = '0836f3ddacaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('uuid', AutoString(), nullable=False))
    op.add_column('plugin', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('plugin', sa.Column('one_time_price', sa.Integer(), nullable=False))
    op.add_column('plugin', sa.Column('count', sa.Integer(), nullable=False))
    op.drop_column('plugin', 'id')
    op.drop_column('plugin', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('plugin', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('plugin', 'count')
    op.drop_column('plugin', 'one_time_price')
    op.drop_column('plugin', 'price')
    op.drop_column('plugin', 'uuid')
    # ### end Alembic commands ###
