"""types fix

Revision ID: 68de4ef4947c
Revises: e34bb20b016a
Create Date: 2024-06-24 12:56:01.957072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '68de4ef4947c'
down_revision: Union[str, None] = 'e34bb20b016a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('plugin', 'image',
               existing_type=sa.VARCHAR(length=200),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin', 'image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2048),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('plugin', 'title',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
