"""alter description

Revision ID: c580ac40d15d
Revises: 16cdfe17a8f1
Create Date: 2024-06-24 12:47:35.593042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c580ac40d15d'
down_revision: Union[str, None] = '16cdfe17a8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
